# fly.toml app configuration file generated for discordbot-wispy-feather-9500 on 2025-03-17T11:11:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discordbot-wispy-feather-9500'
primary_region = 'atl'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
